adjust build-ios

diff --git a/build-ios b/build-ios
--- a/build-ios
+++ b/build-ios
@@ -22,30 +22,31 @@ if [[ -z ${XC_RESULT_BUNDLE-} ]]; then
     logInfo "[Path] Use default result bundle: $XC_RESULT_BUNDLE"
 fi
 if [[ ! -v XC_LOG_FILE ]]; then
-    XC_LOG_FILE="build/xc-build.log"
-    logInfo "[Path] Use default log file: $XC_LOG_FILE"
-elif [[ -n "${CI_CHECK_STYLE_FILE:-}" ]]; then
-    XC_LOG_FILE="build/xc-build.log"
+    export XC_LOG_FILE="build/xc-build.log"
     logInfo "[Path] Use default log file: $XC_LOG_FILE"
 fi
 
 prepeareResultFile "$XC_RESULT_BUNDLE"
+if [[ -n $XC_LOG_FILE ]]; then
+    prepeareResultFile "$XC_LOG_FILE"
+fi
 
 logInfo "[Xcode] Building..."
 
-if [[ -n $XC_LOG_FILE ]]; then
-    # logInfo "Log file: $XC_LOG_FILE"
-    prepeareResultFile "$XC_LOG_FILE"
-    xcCommand build | showProgress || {
-        logError "[Xcode] Build failed:"
-        tail -n 50 "$XC_LOG_FILE"
-        exit 1
-    }
-    logInfo "[Xcode] Building completed."
-    tail -n 4 "$XC_LOG_FILE"
+code=0
+xcCommand build | showProgress || {
+    code=$?
+}
+if [[ $code != 0 ]]; then
+    logError "[Xcode] Building failed."
 else
-    xcCommand build
     logInfo "[Xcode] Building completed."
 fi
 
-"$(dirname $0)/check-result" listIssues summary checkstyle
+resultCommands=("$(dirname $0)/check-result" listIssues summary)
+if [[ -n "${CI_CHECK_STYLE_FILE:-}" ]]; then
+    resultCommands+=("checkstyle")
+fi
+"${resultCommands[@]}"
+
+exit $code
diff --git a/run-tests b/run-tests
--- a/run-tests
+++ b/run-tests
@@ -55,4 +55,35 @@ if [[ ! -d "$XC_RESULT_BUNDLE" ]]; then
     exit 1
 fi
 
+logSection "Test workspace has error"
+xcCommandParametersRestAll
+rm -rf ".test"
+
+hasFailed=0
+export XC_WORKSPACE="tests/samples/Tests.xcworkspace"
+export XC_SCHEME="HasError"
+export XC_DISABLE_CODE_SIGNING=1
+export XC_DESTINATION=mac
+export XC_CLEAN=1
+export XC_BEAUTIFY=0
+export XC_RESULT_BUNDLE=".test/t3.xcresult"
+export CI_CHECK_STYLE_FILE=".test/t3.xml"
+./build-ios || {
+    hasFailed=1
+}
+
+if [[ $hasFailed != 1 ]]; then
+    logError "Build should failed."
+    exit 1
+fi
+
+if [[ ! -f "$CI_CHECK_STYLE_FILE" ]]; then
+    logError "Checkstyle file should be generated."
+    exit 1
+fi
+if [[ ! -d "$XC_RESULT_BUNDLE" ]]; then
+    logError "Result bundle file should be generated."
+    exit 1
+fi
+
 logInfo "[Done]"
